# Generated by Django 3.1.1 on 2020-11-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClothSize',
        ),
        migrations.DeleteModel(
            name='FootwearSize',
        ),
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.DeleteModel(
            name='ItemColor',
        ),
    ]
