# Generated by Django 3.1.1 on 2020-11-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clothsize_footwearsize_itemcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothsize',
            name='cloth_size',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='footwearsize',
            name='footwear_size',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='itemcolor',
            name='item_color',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
