# Generated by Django 3.1.1 on 2020-11-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201124_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(default=10, null=True)),
                ('cloth_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clothsize')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itemcolor')),
                ('footwear_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.footwearsize')),
            ],
        ),
    ]
