# Generated by Django 3.1.1 on 2020-11-24 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_stockquantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='stockquantity',
            options={'verbose_name': 'Stock Quantities'},
        ),
        migrations.AddField(
            model_name='stockquantity',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
    ]
