# Generated by Django 3.1.1 on 2020-11-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201124_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockquantity',
            name='item',
        ),
    ]
