# Generated by Django 3.1.1 on 2020-11-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_stockquantity_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockquantity',
            name='cloth_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clothsize'),
        ),
        migrations.AlterField(
            model_name='stockquantity',
            name='footwear_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.footwearsize'),
        ),
    ]
