# Generated by Django 3.1.1 on 2020-11-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201124_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='stockquantity',
        ),
    ]
