# Generated by Django 3.1.1 on 2020-11-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_item_stockquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockquantity',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
    ]
